artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: "E:/Porjects/Datasets/Vehicle_type_dataset.zip"
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/model.keras

    